syntax on
set autoindent smartindent
set tabstop=4 shiftwidth=4
set showcmd
set incsearch hlsearch
set modeline
colorscheme wombat256mod

" http://www.robmeerman.co.uk/unix/256colours#vim_under_screen_refuses_to_conform
if match($TERMCAP, 'Co#256:') == 0 || match($TERMCAP, ':Co#256:') > 0
	set t_Co=256
endif

set runtimepath+=~/.vim/bundle/syntastic
set runtimepath+=~/.vim/bundle/rust.vim

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_scheme_checkers = [ "scheme" ]
