.PHONY: help install

help: ### show this help
	@cat $(MAKEFILE_LIST) | perl -nle 'm/\A([^\t][^:]+?):.*?### *(.*)\z/ and printf "%-10s %s\n", $$1, $$2'


install: ### recursively setup configs
	$(MAKE) -C vim $@
	$(MAKE) -C zsh $@
	$(MAKE) -C screen $@
	$(MAKE) -C sitelocal $@
